export default [
    {
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Que app é esse?',
      subCategories: ['Gosto de coisas novas', 
						'Conhecer pessoas fora da minha bolha', 
						'Um pouco tímido e indeciso', 
						'Provavelmente está ouvindo música desde quando acordou', 
						'Quando fala de carro não para mais'],
    },
		{
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Histórico e atualizações',
      subCategories: ['v2.5.3', 'Última atualização em: 16/10/2021'],
    },
		{
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Criadores',
      subCategories: ['Meus pais', 'Avós maternos (ficava na casa deles depois da escola'],
    },
    {
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'O que tem de bom?',
      subCategories: ['Um pouco de bom humor depois que vencer a timidez', 
						'Resolver problemas com criatividade e curiosidade', 
						'Um amigo que gosta de ouvir as mais diversas histórias e experiências'],
    },
    {
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Idiomas disponíveis',
      subCategories: ['Português', 'Inglês'],
    },
    {
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Localizado em...',
      subCategories: ['São Paulo - SP', 'Campinas - SP (Quando entrei na faculdade até o começo da pandemia)'],
    },
    {
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Avaliações',
      subCategories: ['Amigos: está sempre presente, mas poderia voltar a ver filme com a gente de sexta à noite', 
						'Família: queriam me ver mais vezes (isolamento)', 
						'Professores: tá participando mais das aulas e se interessando pela matéria'],
    },
		{
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Melhorias',
    	subCategories: [
        'Mais decidido',
        'Menos medo de errar',
      ],
    }, 
    {
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Novidades',
      subCategories: ['React', 'JavaScript', 'Black belt', 'Exercícios 2x na semana'],
    },
		{
      bg: '#2D0536',
      color: '#FCBE4A',
      category: 'Sugestões',
      subCategories: ['Notion', 'Google buscas', 'Facebook', 'Wolfram Alpha'],
    },
  ];